-- Run this SQL in your Supabase SQL Editor to create the tables

-- 1. Users Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  email text not null,
  first_name text,
  last_name text,
  image_url text,
  role text default 'viewer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

drop policy if exists "Enable read access for all users" on public.users;
create policy "Enable read access for all users" on public.users for select using (true);

drop policy if exists "Enable insert access for all users" on public.users;
create policy "Enable insert access for all users" on public.users for insert with check (true);

drop policy if exists "Enable update access for all users" on public.users;
create policy "Enable update access for all users" on public.users for update using (true);


-- 2. Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null,
  title text not null,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.notifications enable row level security;

-- Create a policy that allows users to see only their own notifications
drop policy if exists "Users can view their own notifications" on public.notifications;
create policy "Users can view their own notifications"
on public.notifications for select
using ( user_id = auth.uid()::text ); 

-- For this prototype, we will allow public access (be careful in production!)
drop policy if exists "Enable read access for all users" on public.notifications;
create policy "Enable read access for all users"
on public.notifications for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.notifications;
create policy "Enable insert access for all users"
on public.notifications for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.notifications;
create policy "Enable update access for all users"
on public.notifications for update
using ( true );


-- 3. Processes Table
create table if not exists public.processes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  sheets jsonb not null default '[]'::jsonb,
  versions jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add versions column if it doesn't exist (migration for existing tables)
alter table public.processes add column if not exists versions jsonb not null default '[]'::jsonb;

-- Enable RLS
alter table public.processes enable row level security;

-- Policies for processes
drop policy if exists "Enable read access for all users" on public.processes;
create policy "Enable read access for all users"
on public.processes for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.processes;
create policy "Enable insert access for all users"
on public.processes for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.processes;
create policy "Enable update access for all users"
on public.processes for update
using ( true );


-- 4. Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  process_id bigint, -- Reference to the original process
  version_name text, -- Reference to the version used
  sheets jsonb not null default '[]'::jsonb,
  collaborators jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.projects enable row level security;

-- Policies for projects
drop policy if exists "Enable read access for all users" on public.projects;
create policy "Enable read access for all users"
on public.projects for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.projects;
create policy "Enable insert access for all users"
on public.projects for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.projects;
create policy "Enable update access for all users"
on public.projects for update
using ( true );

drop policy if exists "Enable delete access for all users" on public.projects;
create policy "Enable delete access for all users"
on public.projects for delete
using ( true );

