-- Run this SQL in your Supabase SQL Editor to create the tables

-- 1. Users Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  email text not null,
  first_name text,
  last_name text,
  image_url text,
  role text default 'viewer',
  organization text,
  org_id text, -- Link to Pluto Admin Organization ID
  is_verified boolean default false,
  verified_at timestamp with time zone,
  approval_status text default 'pending', -- 'pending', 'approved', 'rejected'
  is_suspended boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.5 Pending Users Table (Temporary storage until approval)
create table if not exists public.pending_users (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  email text not null,
  first_name text,
  last_name text,
  image_url text,
  role text default 'viewer',
  organization text,
  org_id text,
  is_verified boolean default false,
  approval_status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

drop policy if exists "Enable read access for all users" on public.users;
create policy "Enable read access for all users" on public.users for select using (true);

drop policy if exists "Enable insert access for all users" on public.users;
create policy "Enable insert access for all users" on public.users for insert with check (true);

drop policy if exists "Enable update access for all users" on public.users;
create policy "Enable update access for all users" on public.users for update using (true);

-- Pending Users Policies
alter table public.pending_users enable row level security;
drop policy if exists "Enable all access for all users" on public.pending_users;
create policy "Enable all access for all users" on public.pending_users for all using (true);


-- 2. Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null,
  title text not null,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.notifications enable row level security;

-- Create a policy that allows users to see only their own notifications
drop policy if exists "Users can view their own notifications" on public.notifications;
create policy "Users can view their own notifications"
on public.notifications for select

-- 3. Instance Settings Table (Local Config)
create table if not exists public.instance_settings (
  id bigint generated by default as identity primary key,
  org_id bigint not null, -- ID from Pluto Admin
  org_name text not null,
  org_code text not null,
  license_key text not null,
  status text default 'active',
  jira_url text,
  jira_email text,
  jira_api_token text,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.instance_settings enable row level security;

-- Create policy for instance settings (allow read for verified users)
drop policy if exists "Allow read access for all users" on public.instance_settings;
create policy "Allow read access for all users" on public.instance_settings for select using (true);


-- For this prototype, we will allow public access (be careful in production!)
drop policy if exists "Enable read access for all users" on public.notifications;
create policy "Enable read access for all users"
on public.notifications for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.notifications;
create policy "Enable insert access for all users"
on public.notifications for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.notifications;
create policy "Enable update access for all users"
on public.notifications for update
using ( true );

drop policy if exists "Enable delete access for all users" on public.notifications;
create policy "Enable delete access for all users"
on public.notifications for delete
using ( true );


-- 3. Processes Table (Legacy/Main)
create table if not exists public.processes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  org_id text null,
  name text not null,
  sheets jsonb not null default '[]'::jsonb,
  versions jsonb not null default '[]'::jsonb,
  status text not null default 'draft',
  type text default 'freestyle',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3.1 Table Style Processes
create table if not exists public.table_processes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  org_id text null,
  name text not null,
  sheets jsonb not null default '[]'::jsonb,
  versions jsonb not null default '[]'::jsonb,
  status text not null default 'draft',
  type text default 'table',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3.2 Freestyle Processes
create table if not exists public.freestyle_processes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  org_id text null,
  name text not null,
  sheets jsonb not null default '[]'::jsonb,
  versions jsonb not null default '[]'::jsonb,
  status text not null default 'draft',
  type text default 'freestyle',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for new tables
alter table public.table_processes enable row level security;
alter table public.freestyle_processes enable row level security;

create policy "Enable all access for all users" on public.table_processes for all using (true);
create policy "Enable all access for all users" on public.freestyle_processes for all using (true);

-- Ensure correct defaults and constraints for existing tables
alter table public.processes alter column status set default 'draft';
alter table public.processes alter column status set not null;
alter table public.processes add column if not exists type text default 'freestyle';
alter table public.processes add column if not exists org_id text null;

-- Enable RLS
alter table public.processes enable row level security;

-- Policies for processes
drop policy if exists "Enable read access for all users" on public.processes;
create policy "Enable read access for all users"
on public.processes for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.processes;
create policy "Enable insert access for all users"
on public.processes for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.processes;
create policy "Enable update access for all users"
on public.processes for update
using ( true );

drop policy if exists "Enable delete access for all users" on public.processes;
create policy "Enable delete access for all users"
on public.processes for delete
using ( true );


-- 4. Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  process_id bigint, -- Reference to the original process
  version_name text, -- Reference to the version used
  sheets jsonb not null default '[]'::jsonb,
  collaborators jsonb not null default '[]'::jsonb,
  status text default 'draft',
  type text default 'freestyle',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add type column if it doesn't exist
alter table public.projects add column if not exists type text default 'freestyle';

-- Enable RLS
alter table public.projects enable row level security;

-- Policies for projects
drop policy if exists "Enable read access for all users" on public.projects;
create policy "Enable read access for all users"
on public.projects for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.projects;
create policy "Enable insert access for all users"
on public.projects for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.projects;
create policy "Enable update access for all users"
on public.projects for update
using ( true );

drop policy if exists "Enable delete access for all users" on public.projects;
create policy "Enable delete access for all users"
on public.projects for delete
using ( true );


-- 5. Instance Settings Table (Tracks which organization this instance belongs to)
create table if not exists public.instance_settings (
  id bigint generated by default as identity primary key,
  org_id text not null,
  org_name text not null,
  org_code text not null, -- Unique Organization Code (e.g. ORG_123)
  plan text,
  status text,
  license_key text not null,
  app_version text default '1.0.0', -- Application Version (e.g. 1.2.0)
  server_id text, -- Unique Identifier for the hosted server (e.g. abc-server)
  admin_email text, -- made nullable
  activated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_synced_at timestamp with time zone -- ADDED THIS COLUMN
);

-- Enable RLS
alter table public.instance_settings enable row level security;

-- Policies for instance_settings
drop policy if exists "Enable read access for all users" on public.instance_settings;
create policy "Enable read access for all users"
on public.instance_settings for select
using ( true );

drop policy if exists "Enable insert access for all users" on public.instance_settings;
create policy "Enable insert access for all users"
on public.instance_settings for insert
with check ( true );

drop policy if exists "Enable update access for all users" on public.instance_settings;
create policy "Enable update access for all users"
on public.instance_settings for update
using ( true );

drop policy if exists "Enable delete access for all users" on public.instance_settings;
create policy "Enable delete access for all users"
on public.instance_settings for delete
using ( true );

-- 5. System Logs Table (Real-time Error Tracking)
create table if not exists public.system_logs (
  id bigint generated by default as identity primary key,
  level text default 'info', -- 'info', 'warning', 'error', 'critical'
  category text, -- 'api', 'database', 'auth', 'system'
  message text not null,
  stack_trace text,
  endpoint text,
  user_id text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. API Metrics Table (Performance & Traffic Tracking)
create table if not exists public.api_metrics (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  method text not null,
  latency_ms integer not null,
  status_code integer not null,
  user_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.system_logs enable row level security;
alter table public.api_metrics enable row level security;

-- Policies for system_logs
drop policy if exists "Allow internal logging" on public.system_logs;
create policy "Allow internal logging" on public.system_logs for insert with check (true);
drop policy if exists "Allow admin viewing" on public.system_logs;
create policy "Allow admin viewing" on public.system_logs for select using (true);

-- Policies for api_metrics
drop policy if exists "Allow metrics insertion" on public.api_metrics;
create policy "Allow metrics insertion" on public.api_metrics for insert with check (true);
drop policy if exists "Allow metrics viewing" on public.api_metrics;
create policy "Allow metrics viewing" on public.api_metrics for select using (true);

